apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-weibo-single
  namespace: crawler
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - scrapy
                - crawl
                - single
              env:
                - name: WEIBO_WEIBO_ID
                  value: '4496797961825543'
                - name: WEIBO_COOKIES
                  valueFrom:
                    secretKeyRef:
                      name: weibo
                      key: cookies
                - name: ELASTICSEARCH_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: elasticsearch
                      key: connection_string
                - name: REDIS_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: connection_string
                - name: PROXYPOOL_URL
                  valueFrom:
                    secretKeyRef:
                      name: adslproxy
                      key: universal
                - name: PROXYPOOL_ENABLED
                  value: 'true'
              image: germey/crawler-weibo-single
              name: crawler-weibo-single
              imagePullPolicy: Always
              resources:
                limits:
                  memory: "200Mi"
                  cpu: "150m"
                requests:
                  memory: "200Mi"
                  cpu: "150m"
          restartPolicy: OnFailure